default: compile

compile:
	clang sim8086.c disassembler.c sim86_shared_debug.lib -o sim8086

run_37: compile
	./sim8086 ../asm/listing_0037

run_38: compile
	./sim8086 ../asm/listing_0038

run_39: compile
	./sim8086 ../asm/listing_0039

run_40: compile
	./sim8086 ../asm/listing_0040